# Generated by Django 4.0.2 on 2022-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('technology', models.CharField(max_length=50)),
                ('candidatetype', models.CharField(max_length=50)),
                ('higereducation', models.CharField(max_length=50)),
                ('Passingyear', models.CharField(max_length=50)),
            ],
        ),
    ]
